-- Run in phpMyAdmin after leads table exists (existing KuberFinserve deployments)

CREATE TABLE IF NOT EXISTS partners (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  partner_id VARCHAR(20) DEFAULT NULL,
  full_name VARCHAR(150) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150) NOT NULL,
  city VARCHAR(100) DEFAULT NULL,
  state VARCHAR(100) DEFAULT NULL,
  company_name VARCHAR(150) DEFAULT NULL,
  business_type VARCHAR(80) DEFAULT NULL,
  experience VARCHAR(80) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  must_change_password TINYINT(1) NOT NULL DEFAULT 0,
  otp_hash VARCHAR(255) DEFAULT NULL,
  otp_expires_at TIMESTAMP NULL DEFAULT NULL,
  status ENUM('pending', 'approved', 'rejected', 'suspended') NOT NULL DEFAULT 'pending',
  source VARCHAR(120) DEFAULT NULL,
  page_url VARCHAR(500) DEFAULT NULL,
  extra_data JSON DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  approved_at TIMESTAMP NULL DEFAULT NULL,
  approved_by VARCHAR(80) DEFAULT NULL,
  rejected_at TIMESTAMP NULL DEFAULT NULL,
  rejected_by VARCHAR(80) DEFAULT NULL,
  suspended_at TIMESTAMP NULL DEFAULT NULL,
  suspended_by VARCHAR(80) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_phone (phone),
  UNIQUE KEY uk_email (email),
  UNIQUE KEY uk_partner_id (partner_id),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partner_audit_log (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  partner_row_id INT UNSIGNED NOT NULL,
  action VARCHAR(40) NOT NULL,
  old_status VARCHAR(20) DEFAULT NULL,
  new_status VARCHAR(20) DEFAULT NULL,
  performed_by VARCHAR(80) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_partner_row (partner_row_id),
  INDEX idx_action (action),
  CONSTRAINT fk_partner_audit_partner FOREIGN KEY (partner_row_id) REFERENCES partners(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
