-- Kuberfinserve — run this in Hostinger phpMyAdmin (select your database first)

CREATE TABLE IF NOT EXISTS leads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_lead_id VARCHAR(32) DEFAULT NULL,
  form_type VARCHAR(80) NOT NULL DEFAULT 'lead',
  source VARCHAR(120) DEFAULT NULL,
  crm_channel VARCHAR(40) NOT NULL DEFAULT 'website',
  partner_id VARCHAR(20) DEFAULT NULL,
  form_variant VARCHAR(80) DEFAULT NULL,
  idempotency_key VARCHAR(64) DEFAULT NULL,
  full_name VARCHAR(150) DEFAULT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150) NOT NULL,
  city VARCHAR(100) DEFAULT NULL,
  age VARCHAR(20) DEFAULT NULL,
  employment_type VARCHAR(80) DEFAULT NULL,
  company_name VARCHAR(150) DEFAULT NULL,
  monthly_income VARCHAR(80) DEFAULT NULL,
  work_experience VARCHAR(80) DEFAULT NULL,
  loan_type VARCHAR(120) DEFAULT NULL,
  loan_amount VARCHAR(50) DEFAULT NULL,
  tenure_months VARCHAR(30) DEFAULT NULL,
  existing_emi VARCHAR(50) DEFAULT NULL,
  purpose VARCHAR(120) DEFAULT NULL,
  pan VARCHAR(20) DEFAULT NULL,
  property_value VARCHAR(50) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  page_url VARCHAR(500) DEFAULT NULL,
  extra_data JSON DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  status ENUM('new', 'contacted', 'closed') NOT NULL DEFAULT 'new',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_external_lead_id (external_lead_id),
  UNIQUE KEY uk_idempotency_key (idempotency_key),
  INDEX idx_created (created_at),
  INDEX idx_status (status),
  INDEX idx_loan_type (loan_type),
  INDEX idx_email (email),
  INDEX idx_partner_id (partner_id),
  INDEX idx_crm_channel (crm_channel),
  INDEX idx_phone_loan_created (phone, loan_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Partner onboarding (run after leads table exists)
CREATE TABLE IF NOT EXISTS partners (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  partner_id VARCHAR(20) DEFAULT NULL,
  full_name VARCHAR(150) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150) NOT NULL,
  city VARCHAR(100) DEFAULT NULL,
  state VARCHAR(100) DEFAULT NULL,
  company_name VARCHAR(150) DEFAULT NULL,
  business_type VARCHAR(80) DEFAULT NULL,
  experience VARCHAR(80) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  must_change_password TINYINT(1) NOT NULL DEFAULT 0,
  otp_hash VARCHAR(255) DEFAULT NULL,
  otp_expires_at TIMESTAMP NULL DEFAULT NULL,
  status ENUM('pending', 'approved', 'rejected', 'suspended') NOT NULL DEFAULT 'pending',
  source VARCHAR(120) DEFAULT NULL,
  page_url VARCHAR(500) DEFAULT NULL,
  extra_data JSON DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  approved_at TIMESTAMP NULL DEFAULT NULL,
  approved_by VARCHAR(80) DEFAULT NULL,
  rejected_at TIMESTAMP NULL DEFAULT NULL,
  rejected_by VARCHAR(80) DEFAULT NULL,
  suspended_at TIMESTAMP NULL DEFAULT NULL,
  suspended_by VARCHAR(80) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_phone (phone),
  UNIQUE KEY uk_email (email),
  UNIQUE KEY uk_partner_id (partner_id),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partner_audit_log (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  partner_row_id INT UNSIGNED NOT NULL,
  action VARCHAR(40) NOT NULL,
  old_status VARCHAR(20) DEFAULT NULL,
  new_status VARCHAR(20) DEFAULT NULL,
  performed_by VARCHAR(80) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_partner_row (partner_row_id),
  INDEX idx_action (action),
  CONSTRAINT fk_partner_audit_partner FOREIGN KEY (partner_row_id) REFERENCES partners(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS website_visitors (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_visitor_id VARCHAR(64) NULL,
  city VARCHAR(100) NOT NULL,
  name VARCHAR(200) NULL,
  phone VARCHAR(15) NULL,
  email VARCHAR(255) NULL,
  page_url VARCHAR(500) NULL,
  referrer VARCHAR(500) NULL,
  utm_source VARCHAR(120) NULL,
  utm_medium VARCHAR(120) NULL,
  utm_campaign VARCHAR(120) NULL,
  session_id VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_external_visitor_id (external_visitor_id),
  KEY idx_city (city),
  KEY idx_phone (phone),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
