export interface CibilFaq {
  q: string
  a: string
}

export const CIBIL_PAGE = {
  title: 'CIBIL Score Assistance',
  shortTitle: 'CIBIL',
  description:
    'Understand your credit profile, improve loan eligibility and unlock better interest rates. Expert guidance on credit score health — subject to bureau data and lender policy.',
  heroImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1920&q=85',
  metaTitle: 'CIBIL Score Check & Improvement Guidance | KuberFinserve',
  metaDescription:
    'Get expert CIBIL / credit score assistance. Learn score ranges, factors affecting your score and tips to improve loan eligibility. Subject to bureau & lender norms.',
  keywords:
    'CIBIL score, credit score India, improve CIBIL, CIBIL check, loan eligibility score, TransUnion CIBIL, credit report guidance, KuberFinserve',
} as const

export const CIBIL_SCORE_BANDS = [
  {
    range: '300 – 549',
    label: 'Poor',
    desc: 'High risk profile. Loan approvals are difficult; focus on clearing dues and correcting errors.',
    color: 'bg-red-100 text-red-800 border-red-200',
  },
  {
    range: '550 – 649',
    label: 'Fair',
    desc: 'Limited options. Some NBFCs may consider with higher rates or additional collateral.',
    color: 'bg-amber-100 text-amber-900 border-amber-200',
  },
  {
    range: '650 – 749',
    label: 'Good',
    desc: 'Preferred by many lenders. Competitive rates possible with stable income.',
    color: 'bg-brand-100 text-brand-900 border-brand-200',
  },
  {
    range: '750 – 900',
    label: 'Excellent',
    desc: 'Strong approval odds and best available pricing with partner banks & NBFCs.',
    color: 'bg-emerald-100 text-emerald-900 border-emerald-200',
  },
] as const

export const CIBIL_HIGHLIGHTS = [
  'Understand your credit report factors',
  'Identify errors & dispute guidance',
  'EMI discipline & utilisation tips',
  'Loan-ready profile assessment',
  'Better rate negotiation support',
  'Multi-lender eligibility mapping',
  'Personalised improvement roadmap',
  'Dedicated credit advisor support',
] as const

export const CIBIL_FACTORS = [
  {
    title: 'Payment History',
    desc: 'On-time EMIs and credit card payments carry the highest weight. Late payments hurt your score.',
  },
  {
    title: 'Credit Utilisation',
    desc: 'Keep revolving credit usage ideally below 30% of available limit for a healthier score.',
  },
  {
    title: 'Credit Mix & Age',
    desc: 'A mix of secured and unsecured credit with longer account age generally looks stronger.',
  },
  {
    title: 'New Enquiries',
    desc: 'Multiple hard inquiries in a short span can temporarily lower your score.',
  },
  {
    title: 'Outstanding Debt',
    desc: 'High outstanding balances relative to income may impact both score and loan eligibility.',
  },
  {
    title: 'Report Accuracy',
    desc: 'Wrong personal details, duplicate accounts or settled-but-shown-active loans need correction.',
  },
] as const

export const CIBIL_IMPROVE_TIPS = [
  'Pay all EMIs and credit card dues on or before the due date',
  'Reduce credit card outstanding — aim for lower utilisation',
  'Avoid applying for multiple loans/cards within a short period',
  'Keep old accounts active if they have a clean repayment history',
  'Review your credit report regularly for errors',
  'Settle overdue accounts and request updated status from lenders',
  'Maintain a healthy mix of credit without over-leveraging',
  'Build a stable income & banking track record before large loan applications',
] as const

export const CIBIL_PROCESS = [
  {
    step: '01',
    title: 'Share Profile',
    desc: 'Tell us about income, existing loans and credit concerns.',
  },
  {
    step: '02',
    title: 'Review Guidance',
    desc: 'Our advisors help interpret common score drivers and risk flags.',
  },
  {
    step: '03',
    title: 'Action Plan',
    desc: 'Get a practical roadmap and loan options suited to your profile.',
  },
] as const

export const CIBIL_WHY = [
  'Dedicated advisors for credit & loan readiness',
  'Compare 100+ bank & NBFC partners',
  'Transparent process — no false guarantees',
  'PAN India support with digital documentation',
  'Guidance aligned to RBI-compliant lending practices',
  'End-to-end help from score hygiene to loan application',
] as const

export const CIBIL_DISCLAIMER =
  '*CIBIL® is a registered trademark of TransUnion CIBIL Limited. KuberFinserve is not affiliated with, endorsed by, or an agent of TransUnion CIBIL. Credit scores and reports are generated by authorised credit information companies. We provide advisory guidance only and do not generate, alter or guarantee any credit score. Loan approval, interest rates and eligibility remain solely at the discretion of the respective Bank or NBFC. Past improvement tips do not guarantee score increase or loan sanction.'

export const CIBIL_FAQS: readonly CibilFaq[] = [
  {
    q: 'What is a CIBIL score?',
    a: 'A CIBIL score (commonly referring to the TransUnion CIBIL credit score) is a three-digit number typically ranging from 300 to 900 that summarises your credit history. Lenders use it along with income and other factors to assess loan and credit card applications.',
  },
  {
    q: 'What is a good CIBIL score for a loan?',
    a: 'Most banks and NBFCs prefer a score of 650+, while 750+ generally unlocks better approval odds and pricing. Exact cut-offs vary by lender, product and overall profile. Subject to eligibility.',
  },
  {
    q: 'Does KuberFinserve check or generate my CIBIL score?',
    a: 'No. Official scores are provided by authorised credit information companies (such as TransUnion CIBIL) or through their licensed channels. We offer advisory guidance to help you understand factors that influence eligibility and prepare for loan applications.',
  },
  {
    q: 'Will checking my score reduce it?',
    a: 'Soft checks (self-enquiry via authorised portals) typically do not reduce your score. Hard inquiries from lenders when you apply for credit may have a temporary impact if done frequently.',
  },
  {
    q: 'How long does it take to improve a credit score?',
    a: 'Improvement depends on your history, overdue amounts and repayment behaviour. Consistent on-time payments and lower utilisation over several months usually show positive movement — there is no guaranteed timeline.',
  },
  {
    q: 'Can I get a loan with a low CIBIL score?',
    a: 'Some lenders may consider profiles with lower scores with secured products, co-applicants or higher pricing. Options are limited and never guaranteed. Our advisors can help map realistic alternatives subject to lender policy.',
  },
  {
    q: 'What documents are needed for CIBIL assistance?',
    a: 'Typically KYC (PAN, Aadhaar), recent credit report if available, loan/credit card statements and basic income proof help our advisors give relevant guidance.',
  },
  {
    q: 'Does improving my score guarantee loan approval?',
    a: 'No. A stronger score improves eligibility odds but final sanction depends on income, existing obligations, documentation, property/asset norms and lender underwriting.',
  },
  {
    q: 'How often should I review my credit report?',
    a: 'At least once every few months, and always before a major loan application, to spot errors or overdue updates early.',
  },
  {
    q: 'Is CIBIL assistance a paid service?',
    a: 'Share your details via the form and our team will explain the assistance process. We do not promise score changes or approvals in exchange for payment claims.',
  },
]
